##### cloud configuration #####

#iot thing and device information
device_id = stech-123

#api details
api_url = https://4rqb6z06lh.execute-api.us-east-1.amazonaws.com/default/sigmaWeldConfig?device_id
sss_url = https://sigma-weld-config.s3.us-east-1.amazonaws.com

#mqtt details
mqtt_port = 1883
mqtt_topic = sigma/test_557
mqtt_host = 198.38.87.90