##### General settings #####

#log settings
log_folder = /sd/log

# measurement settings
min_current = 20
voltage_f = 4
current_slope = 40
current_offset = 3.4
adc_samples = 50

# device settings
interval_ms = 900
max_ram_record = 100
buffer_size= 2
